name: Handle Reminder

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:
  handle-reminder:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Handle reminder labels
        uses: iobroker-bot-orga/action-handle-reminder@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          process-all: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
          mail_server_address: ${{ secrets.IOBBOT_MAIL_SERVER_ADDRESS }}
          mail_server_port: ${{ secrets.IOBBOT_MAIL_PORT }}
          mail_secure: ${{ secrets.IOBBOT_MAIL_SECURE }}
          mail_username: ${{ secrets.IOBBOT_MAIL_USERNAME }}
          mail_password: ${{ secrets.IOBBOT_GMXMAIL }}
          mail_to: ${{ secrets.IOBBOT_MAIL_TO }}
          mail_from: ${{ secrets.IOBBOT_MAIL_FROM }}
